/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sj4399_import_peso_NativeUtil */

#ifndef _Included_com_sj4399_import_peso_NativeUtil
#define _Included_com_sj4399_import_peso_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sj4399_import_peso_NativeUtil
 * Method:    test1
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_sj4399_import_1peso_NativeUtil_test1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
